---
title: "flexdashboard + shiny_prerendered"
output: 
 flexdashboard::flex_dashboard:
   orientation: columns
   source_code: embed
runtime: shiny
---

```{r context="setup", include=FALSE}
library(shiny)
library(ggplot2)
library(dplyr)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r context="render"}
checkboxGroupInput("cyl", "Cylinders", choices = c("4", "6", "8"),
                   selected = c("4", "6", "8"), inline = TRUE
                   )

sliderInput("hp", "Horsepower",
            min = min(mtcars$hp), max = max(mtcars$hp),
            value = range(mtcars$hp)
            )

radioButtons("plot_type", "Weight plot type", 
             choices = c("Histogram", "Violin plot"), selected = c("Histogram"))
```

Outputs
-----------------------------------------------------------------------

### Scatterplot of weight and miles per gallon

```{r context="server"}
mpg_subset <- reactive({
  mtcars %>%
    filter(
      hp >= input$hp[1],
      hp <= input$hp[2],
      cyl %in% input$cyl
    )
})

output$scatter <- renderPlot({
  ggplot(mpg_subset(), aes(x = wt, y = mpg, color = factor(cyl))) +
    geom_point()
})
```

```{r context="render"}
plotOutput("scatter")
```

### Histogram or violin plot of weight

```{r context="server"}
output$weight_plot <- renderPlot({
  
  if(input$plot_type == "Histogram"){
    ggplot(mpg_subset(), aes(x = wt)) +
      geom_histogram(binwidth = 0.25) +
      coord_cartesian(xlim = range(mtcars$wt)) 
  }
  else {
    ggplot(mpg_subset(), aes(y = wt, x = factor(1))) +
      geom_violin()
  }
    
})
```

```{r context="render"}
plotOutput("weight_plot")
```
